import { Inter } from "next/font/google";
import "./globals.css";
import {ApolloWrapper} from './ApolloWrapper'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ApolloProvider client={client}>{children}</ApolloProvider> */}
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
